# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6] # [3.6, 3.7, 3.8]
        poetry-version: [1.0] # [1.0, 1.0.10]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    # Runs a single command using the runners shell (toy sanple)
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Poetry installation and test
      run: |
        poetry install
        which pip
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install flake8 pytest
        which pip
    - name: Test with pytest
      run: pytest
